
export const jugeResultDISC = {
  influence: {
    color: "#ffc107",
    type_people: "người chia sẻ",
    group: "ảnh hưởng",
    describe:
      "Đây là mẫu Người Nhiệt Tình. Đây chắc hẳn chính là mẫu người mà mọi người đều yêu thích. Làm việc với người nhóm này có thể giúp bạn luôn vui vẻ và tràn đầy năng lượng sau những công việc căng thẳng.",
    sub_describe: "Vui là chính",
    feature: [
      "Xu hướng hành động: Thuyết phục",
      "Nhu cầu: Sự đồng thuận, ủng hộ của người khác",
      "Thích công việc: Có liên quan đến con người",
      "Cảm thấy thoải mái khi: ở môi trường XH thân thiện",
      "Cảm thấy có giá trị: Được nhìn nhận và khen thưởng",
    ],
    learn_style: [
      "Thích học nhóm hơn là tự học",
      "Không tạo phương thức học tập riêng, mà sẽ thực hiện theo phân công của nhóm hay sự góp ý của người khác.",
      "Không thích đi sâu vào các vấn đề hoặc các môn học đòi hỏi khắc khe.",
      "Hay nảy ra các lý thuyết, ý tưởng và phương pháp học tập mới.",
      "Thích vui chơi và muốn được giải trí trong khi học.",
      "Thích thuyết trình và hướng dẫn người khác",
    ],
    advise_career_hobby: [
      "Bạn có thể cảm thấy nhàm chán với những công việc lặp đi lặp lại và không có gì mới mẻ, bạn đừng nên chọn những công việc liên quan đến báo cáo, con số hoặc sổ sách.",
      "Bạn thích làm những công việc được tiếp xúc với nhiều người và trong môi trường làm việc năng động. Chính vì thế bạn sẽ ức chế nếu phải làm những công việc chỉ “ngồi” 1 chỗ hoặc yêu cầu khả năng làm việc độc lập như trong lãnh vực công nghệ hoặc nghiên cứu khoa học.",
    ],
    advise_career_consider: [
      "Kế toán",
      "Nhân viên ghi sổ kế toán (Bookkeeper)",
      "Chuyên Viên Xử Lý Báo Cáo",
      "Chuyên viên phân tích tài chính",
      "Kỹ thuật viên xử lý dữ liệu",
      "Kỹ sư CNTT",
      "Kỹ sư phần mềm",
      "Chuyên gia bảo mật",
      "Lập trình viên điện thoại",
      "Các nghề liên quan đến khoa học (Sinh học, dịch tễ học…)",
      "Luật",
      "Biên tập viên",
      "Tiếp viên hàng không",
    ],
    advise_course:
      "Tư duy logic, Kỹ năng quản lý thời gian, Kỹ năng lắng nghe, Kỹ năng thể hiện sự cảm thông, Kỹ Năng Ứng Phó Với Căng Thẳng Và Kiểm Soát Cảm Xúc, Quản lý dự án, Kỹ năng xử lý từ chối, Làm Thế Nào Để Đối Phó Với Cảm Giác Bị Cô Lập Tại Nơi Làm Việc",

    banner: "https://rightpath.edu.vn/images/Creative%20thinking-bro.png",
    job: [
      "Chuyên viên Tổ chức sự kiện",
      "Chuyên viên kinh doanh Bất động sản",
      "Chuyên viên Marketing",
      "Chuyên viên viết quảng cáo",
      "Nhân viên sáng tạo nội dung",
      "Chuyên viên quan hệ công chúng",
      "Chuyên viên truyền thông",
      "Đại lý du lịch",
      "Nhà báo",
      "Chuyên viên Thiết kế thời trang",
      "Thiết kế nội thất",
      "Diễn viên",
      "Biên tập viên",
      "Tiếp viên hàng không",
    ],
    major:
      "Marketing, Quản lý thể dục thể thao, Tổ chức sự kiện thể thao, Bất động sản, Quản trị kinh doanh, Quản trị du lịch và khách sạn, Quản trị dịch vụ du lịch và lữ hành, Truyền thông chuyên nghiệp, Điện ảnh, Ca hát, Báo chí, Thiết kế thời trang…, Luật…, Biên tập viên, Tiếp viên hàng không…",
  },

  steady: {
    color: "#0d6efd",
    type_people: "chuyên gia hòa giải",
    group: "kiên định",
    describe:
      "Đây là mẫu Người hỗ trợ. Đây là người bạn có thể hoàn toàn tin tưởng khi chia sẻ tâm sự của bản thân. Người chia sẻ thường có khả năng giao tiếp tốt biết cách đem ra những lời khuyên hữu ích để kết nối mọi người thu hẹp khoảng cách giữa mọi người.",
    sub_describe: "Ai kêu tui đó, có tui đây",
    feature: [
      "Xu hướng hành động: Kiên nhẫn",
      "Nhu cầu: Được sắp đặt sẵn",
      "Thích công việc: Được lập kế hoạch trước",
      "Cảm thấy thoải mái khi: Được nắm quyền quyết định",
      "Cảm thấy có giá trị: Được hỗ trợ, đóng góp; Thích nghi với mọi người, mọi hoàn cảnh",
      "Cảm thấy thoải mái khi: Được tham gia hoạt động nhóm",
    ],
    learn_style: [
      "Thích học nhóm và các thành viên trong nhóm đều hỗ trợ nhau",
      "Thích được hướng dẫn và qui trình rõ ràng",
      "Thích được quan sát và sau đó thực hành dưới sự giám sát và góp ý của thầy cô hoặc trưởng nhóm",
      "Thích học những môn đã có dẫn chứng cụ thể hơn là những môn yêu cầu bạn chứng minh",
      "Trong 4 nhóm D.I.S.C, những người thuộc nhóm S là người học dễ tiếp thu và là những người kiên nhẫn nhất",
    ],
    advise_career_hobby: [
      "Nhóm S luôn cố gắng hòa hợp với mọi người. Do đó, bạn có khả năng phù hợp môi trường làm việc:",
      "Được hỗ trợ, tôn trọng và bảo vệ",
      "Được quan tâm, chăm sóc người khác",
      "Có khả năng giải quyết xung đột và lắng nghe cả hai bên. Có thể phát triển mạnh trong lĩnh vực dịch vụ khách hàng",
      "Có thể không thích làm việc đòi hỏi làm việc độc lập như kỹ thuật, máy tính hoặc trong môi trường cạnh tranh như sales",
    ],
    advise_career_consider: [
      "Nhân viên kinh doanh",
      "Môi giới chứng khoán",
      "Nhân viên Tài chính ngân hàng",
      "Chuyên viên phân tích tài chính",
      "Kế toán",
      "Kiểm toán",
      "Kỹ sư Điện - Điện tử",
      "Kỹ sư công nghệ thông tin",
      "Lập trình viên CNTT",
      "Kỹ sư máy tính",
      "Kỹ sư hóa học",
      "Kỹ sư cơ khí",
    ],
    advise_course:
      "Kỹ năng thể hiện bản thân, Kỹ năng giao tiếp, Kỹ năng giải quyết vấn đề, Kỹ năng phản hồi, Kỹ năng Tư duy phản biện, Kỹ năng làm việc nhóm., Kỹ Năng Ứng Phó Với Căng Thẳng Và Kiểm Soát Cảm Xúc",

    banner: "https://rightpath.edu.vn/images/Mental%20health-bro.png",
    job: [
      "Chuyên gia tổ chức sự kiện",
      "Chuyên viên dịch vụ khách hàng",
      "Nhân viên tư vấn kinh doanh",
      "Nhân viên hành chính nhân sự",
      "Bác sĩ tâm lý lâm sàng",
      "Tham vấn tâm lý",
      "Giáo viên",
      "Thủ thư",
      "Bác sĩ",
      "Y tá",
      "Nha sĩ",
      "Nhà sản xuất phim",
    ],
    major:
      "Marketing, Quản trị kinh doanh (Chuyên ngành Quản lý nhân sự), Quản lý thể dục thể thao, Tâm lý học, Tâm lý học lâm sàng, Khoa học thư viện, Truyền thông chuyên nghiệp, Truyền thông đa phương tiện, Đạo diễn Sân khấu điện ảnh, Y khoa, Điều dưỡng, Y dược học cổ truyền…",
  },

  dominance: {
    color: "#dc3545",
    type_people: "người lãnh đạo",
    group: "thống lĩnh",
    describe:
      "Đây là mẫu Người Lãnh Đạo, tính cách có xu hướng quyết đoán, mãnh liệt và đầy tham vọng. Họ thường thực dụng, hướng tới kết quả, làm việc nhanh chóng và đưa ra quyết định một cách chắc chắn và khách quan. Người thủ lĩnh thích tự chủ làm việc và có khả năng bị kiệt sức nếu làm những công việc theo yêu cầu của nhiều bên, vì có thể là do họ thích kiểm soát tình huống hơn là bị đặt trong tình huống phải giải quyết công việc với người khác.",
    sub_describe: "Chơi là phải thắng, làm phải có kết quả",
    feature: [
      "Xu hướng hành động: Rất chắc chắn và quyết đoán khi đưa ra quyết định",
      "Nhu cầu: Nắm quyền kiểm soát",
      "Thích công việc: Có nhiều thử thách",
      "Cảm thấy thoải mái: Khi được nắm quyền quyết định",
      "Cảm thấy có giá trị: Khi làm những công việc thử thách, đạt được kết quả cao và được công nhận thành tựu",
    ],
    learn_style: [
      "Thích tự học hơn là học nhóm",
      "Có động lực riêng trong học tập, học vì lý do của bản thân",
      "Thích học hỏi với tốc độ nhanh và chỉ có thể tập trung trong khoảng thời gian ngắn",
      "Có thể thích tự thiết kế cách học tập riêng của mình",
      "Luôn hỏi trước nội dung, giáo trình, lịch trình, thậm chí chất vấn cách giảng dạy hoặc chủ đề môn học",
      "Có xu hướng mất kiên nhẫn với những chủ đề không thích",
    ],
    advise_career_hobby: [
      "Không thích những công việc bị quản lý chặt chẽ, ít quyền tự chủ hoặc có nhịp độ chậm",
      "Không thích những công việc đòi hỏi sự quan tâm đến nhu cầu cá nhân hoặc xây dựng mối quan hệ lâu dài",
      "Cảm thấy thoải mái khi được làm những công việc dẫn dắt và quản lý người khác",
      "Thích những công việc có tính cạnh tranh và đạt kết quả cao",
    ],
    advise_career_consider: [
      "Nhân viên hành chính",
      "Trợ lý",
      "Kỹ thuật viên",
      "Thủ thư",
      "Tham vấn tâm lý",
    ],
    advise_course:
      "Tư duy linh hoạt, Kỹ năng thể hiện sự cảm thông, Kỹ năng phản hồi, kỹ năng quản lý, Kỹ năng ứng phó với căng thẳng và kiểm soát cảm xúc, Thay đổi tư duy - ngừng kiểm soát người khác, Quản lý dự án",

    banner: "https://rightpath.edu.vn/images/Fire%20hair-bro.png",
    job: [
      "Đại lý kinh doanh",
      "Môi giới bất động sản",
      "Luật sư",
      "Môi giới chứng khoán",
      "Cố vấn - Coaching",
      "Công an",
      "Điều tra viên/Thám tử tư",
      "PT - huấn luyện viên cá nhân",
    ],
    major:
      "Quản trị kinh doanh, Kinh doanh quốc tế, Quản lý thể dục thể thao, Bất động sản, Kinh tế - Tài chính, Quản trị du lịch và khách sạn, Công an, Luật…",
  },

  compliant: {
    color: "#198754",
    type_people: "người tỉ mỉ",
    group: "tuân thủ",
    describe:
      "Đây là mẫu Người tỉ mỉ. Người tỉ mỉ luôn chú ý đến những chi tiết nhỏ và có thể dành toàn bộ thời gian của họ để phân tích khám phá ra một điều gì đó. Người tỉ mỉ để ý đến độ chính xác trong công việc, họ luôn muốn duy trì sự ổn định trong công việc.",
    sub_describe: "Nói có dữ liệu, mách có dữ kiện",
    feature: [
      "Xu hướng hành động: Quan sát và suy ngẫm các vấn đề",
      "Nhu cầu: Mọi thứ phải đạt chuẩn. Có quan điểm mọi việc nên đúng ngay khi bắt đầu",
      "Thích công việc: Có cấu trúc rõ ràng",
      "Cảm thấy thoải mái: Khi được sắp xếp và lập kế hoạch",
      "Cảm thấy có giá trị: Khi làm việc chính xác và đúng",
      "Thích nói đến các dữ liệu và dữ kiện vì theo nhóm C chỉ có dữ liệu mới mang đến thông tin chính xác",
      "Nhóm C có xu hướng đặt câu hỏi thay vì nói, cho phép thu thập nhiều dữ liệu hơn",
    ],
    learn_style: [
      "Nhóm C có thể phát hiện một lỗi chính tả nhỏ xíu trong đống tài liệu dày cộp",
      "Nhóm C rất nghiêm túc trong học tập và có xu hướng hỏi thầy cô hoặc tìm tài liệu để đọc nếu chưa rõ",
      "Khi một điều gì đó được đề xuất, nhóm C sẽ suy nghĩ thấu đáo từng chi tiết về cách thức hoạt động và quy trình của nó",
      "Nhóm C cực kỳ chi tiết và luôn hoàn thành nhiệm vụ được giao một cách kỹ lưỡng",
    ],
    advise_career_hobby: [
      "Nhóm C là người theo hướng dữ liệu, logic và phân tích, phù hợp nhất với những nghề nghiệp độc lập và dựa trên dữ liệu như trong lãnh vực CNTT",
      "Nhóm C thích làm việc độc lập nhưng vẫn muốn chia sẻ kết quả, có thể thích những công việc có ít tương tác xã hội như một nhà phân tích tài chính hoặc chuyên gia tính toán",
      "Nhóm C có lý trí, logic, và sợ rủi ro, có thể tránh những công việc có nhiều rủi ro, không có tính logic như các công việc kinh doanh hoặc nghệ thuật",
    ],
    advise_career_consider: [
      "Nhân viên Kinh doanh",
      "Chuyên viên Thiết kế thời trang",
      "Chuyên viên Thiết kế đa phương tiện",
      "Chuyên viên Thiết kế đồ họa",
      "Chuyên viên Thiết kế hậu cần điện ảnh",
      "Nhà Thiết kế thời trang",
      "Đạo diễn phim ảnh",
      "Diễn viên",
      "Ca sĩ",
      "Biên tập viên",
      "Nhà báo",
    ],
    advise_course:
      "Kỹ năng giao tiếp, Kỹ năng thể hiện sự cảm thông, Kỹ năng phản hồi, Kỹ năng quản lý, Kỹ Năng Ứng Phó Với Căng Thẳng Và Kiểm Soát Cảm Xúc, Kỹ năng Quản lý dự án",

    banner: "https://rightpath.edu.vn/images/Manage%20money-bro.png",
    job: [
      "Chuyên viên phát triển ứng dụng",
      "Kỹ sư phần mềm",
      "Chuyên gia phân tích dữ liệu",
      "Kỹ thuật viên CNTT",
      "Chuyên gia phân tích tài chính",
      "Kế toán",
      "Giám đốc điều hành",
      "Kỹ sư hóa",
      "Kỹ sư xây dựng",
      "Kỹ sư điện – điện tử",
      "Kỹ sư môi trường",
      "Kỹ sư Cơ khí",
      "Kỹ sư dầu Dầu khí",
      "Nhà nghiên cứu vi sinh",
      "Nhà nghiên cứu địa chất",
      "Kỹ sư kỹ thuật hệ thống công nghiệp",
      "Phi công",
    ],
    major:
      "Công nghệ thông tin, Kinh tế - Tài chính, Tài chính ngân hàng, Kế toán, Kỹ thuật hóa học, Kỹ thuật vi sinh, Thống kê học, Kỹ thuật Điện – Điện tử, Kỹ thuật Cơ khí, Kỹ thuật xây dựng, Kỹ thuật Dầu khí, Địa chất học, Hàng không…",
  },
};
